version: '3.9'

services:
    web:
        container_name: backDjango
        restart: unless-stopped
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
        links:
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/app

    db:
        container_name: postgredb
        restart: unless-stopped
        image: "postgres"
        ports:
            - "5432:5432"
        shm_size: 128mb
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB

    pgadmin:
        container_name: pgadmin
        image: "dpage/pgadmin4"
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "5051:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD