# Generated by Django 5.1 on 2024-08-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='date',
        ),
    ]
