# Generated by Django 5.1 on 2024-08-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_userbalance_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbalance',
            table=None,
        ),
    ]
